//Auto generated by tgf util
//created at 2023-12-10 23:58:49.69684 +0800 CST m=+0.011772938

package propservice

import (
	"github.com/thkhxm/tgf/tgf-tutorial/common/model"

	"github.com/thkhxm/tgf/rpc"
)

var propService = &rpc.Module{Name: "prop", Version: "v1.0.0"}

var (
	GetUserPropCount = rpc.ServiceAPI[*model.GetUserPropArgs, *model.GetUserPropReply]{
		ModuleName:  propService.Name,
		Name:        "GetUserPropCount",
		MessageType: propService.Name + "." + "GetUserPropCount",
	}
)
