//Auto generated by tgf util
//created at 2023-12-11 00:04:11.720306 +0800 CST m=+0.010060313

package api

import (
	"github.com/thkhxm/tgf/rpc"

	"github.com/thkhxm/tgf/tgf-tutorial/common/pb"
)

var hallService = &rpc.Module{Name: "hall", Version: "v1.0.0"}

var (
	HelloWorld = rpc.ServiceAPI[*pb.HelloWorldRequest, *pb.HelloWorldResponse]{
		ModuleName:  hallService.Name,
		Name:        "HelloWorld",
		MessageType: hallService.Name + "." + "HelloWorld",
	}

	LoadUserData = rpc.ServiceAPI[*pb.LoadUserDataRequest, *pb.LoadUserDataResponse]{
		ModuleName:  hallService.Name,
		Name:        "LoadUserData",
		MessageType: hallService.Name + "." + "LoadUserData",
	}

	Login = rpc.ServiceAPI[*pb.LoginRequest, *pb.LoginResponse]{
		ModuleName:  hallService.Name,
		Name:        "Login",
		MessageType: hallService.Name + "." + "Login",
	}
)

const ()
