//Auto generated by tgf util
//created at 2023-12-10 20:53:16.230916 +0800 CST m=+0.009333679

package api

import (
	"github.com/thkhxm/tgf/rpc"

	"github.com/thkhxm/tgf/tgf-tutorial/common/pb"
)

var hallService = &rpc.Module{Name: "hall", Version: "v1.0.0"}

var (
	HelloWorld = rpc.ServiceAPI[*pb.HelloWorldRequest, *pb.HelloWorldResponse]{
		ModuleName:  hallService.Name,
		Name:        "HelloWorld",
		MessageType: hallService.Name + "." + "HelloWorld",
	}

	Login = rpc.ServiceAPI[*pb.LoginRequest, *pb.LoginResponse]{
		ModuleName:  hallService.Name,
		Name:        "Login",
		MessageType: hallService.Name + "." + "Login",
	}
)

const ()
